const FILETYPES = {
    UNDER_GRAD_DIPLOMA: 'UGD',
    POST_GRAD_DIPLOMA: 'PGD',
    PHD_DIPLOMA: 'PHD',
    CV: 'CV',
    WORK_EXPERIENCE: 'WXP',
    CERTIFICATE: 'CRT',
    RECOMMENDATION: 'RCM',
    MILITARY_CERT: 'MCT',
    AFFIRMATION: 'AFR',
}

export default FILETYPES;